### ISSUE TITLE
The interface allow to select 2 different filter for the same column => no result

### ISSUE THREAD

**Issue by daverick** [cqliu1/canvas-multi-filter#2]
As the multi filter is making a AND between the conditions, if you select two different filters for the same columns you get no result, which is kind of logically normal.
What is not normal is that you can select more than one filter for the same column.

Could it be changed? or is it something that is expected and that I don't understand?

**Comment by cqliu1** [comment]
For now, let's limit the user to one selected filter value per column.

**Comment by cqliu1** [comment]
Closed with f5422c2642668546bae319e4fcd6075ca6af548a.
